[build]
  command = "npm install"
  functions = "netlify/functions"
  publish = "public"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["mongoose", "mongodb"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[dev]
  targetPort = 8888
  publish = "public"
  framework = "#custom"

[dev.command]
  development = "npm run dev"
  production = "npm start"
